
version: 2

sources: 
  - name: xyz
    description: this is clone of snowflake original table clone
    database: ANALYTICS
    schema: DBT_SPATEL
    tables:
      - name: raw_customer
        description: "xyz 123"
      - name: orders
        description: original order table
        columns:
          - name: orderid
            description: primaryKey for orders
      - name: product
models:
  - name: Dev_customer
    description: "DBT description for Dev customer table"
    columns:
      - name: NAME
        description: "Скажите пожалуйста, как пройти в палату?Скажите пожалуйста, как пройти в палату? from GIT Warning Permanently added 'ip-10-13-89-128.alation-test.com' (ED25519) to the list of known hosts."

  - name: dev_order
    description: "DBT descriptin for dev order"
    columns:
      - name: ORDERID
        description: "Uniquely identified a product"
      - name: ORDERDATE
        description: "Date of Order placed"
      - name: SHIPMODE
        description: "Type of shipment"
  - name: dev_product
    description: "Deb description for product level information"
    columns:
      - name: PRODUCTNAME
        description: "Name given to a product"
